import type { Metadata } from 'next'
import AuthProvider from './auth/Provider'
import './globals.css'
import Navbar from './Navbar'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
interface Props {
  readonly children: React.ReactNode
}

export default function RootLayout({ children }: Props) {
  return (
    <html lang='en' data-theme='dark'>
      <AuthProvider>
        <body>
          <Navbar />
          <main className='p-5'>{children}</main>
        </body>
      </AuthProvider>
    </html>
  )
}
